  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJxrFJjCKQOKQ9yX/SBxtyj23n4VVYLgiLlk2/W61GBo ansible_key"
      